mqtt:
  host: 127.0.0.1  # MQTT 伺服器 IP(192.168.x.x,127.0.0.1 if mqtt server in the same host)
  user: your_mqtt_username
  password: your_mqtt_password

cameras:
  front_door:
    ffmpeg:
      inputs:
        - path: rtsp://username:password@camera_ip:554/stream
          roles:
            - detect
            - rtmp
    width: 1280
    height: 720
    fps: 5
