version: '3'
services:
  nginx:
    image: nginx:alpine
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - website_data:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - samba
    restart: unless-stopped

  samba:
    image: dperson/samba
    container_name: smb_server
    ports:
      - "445:445"    # SMB
      - "139:139"    # SMB
      - "137:137/udp" # NetBIOS
      - "138:138/udp" # NetBIOS
    volumes:
      - website_data:/share
    environment:
      - TZ=Asia/Taipei
      - USERID=1000
      - GROUPID=1000
    command: '-s "website;/share;yes;no;yes;all;none;none" -u "webadmin;password"'
    restart: unless-stopped

volumes:
  website_data:
